let data = [
    {"schoolName": "Globetek Science Foundation", "city": "Makati City", "schoolID": 407698},
    {"schoolName": "Lorenzo Ruiz Academy", "city": "Binondo", "schoolID": 406330},
    {"schoolName": "Tiong Se Academy", "city": "Binondo", "schoolID": 406335},
    {"schoolName": "ABE International Business College", "city": "Caloocan City", "schoolID": 400942},
    {"schoolName": "AMA Computer College", "city": "Caloocan City", "schoolID": 400947},
    {"schoolName": "Asian Institute of Computer Studies", "city": "Caloocan City", "schoolID": 400952},
    {"schoolName": "Colegio de San Gabriel Arcangel", "city": "Caloocan City", "schoolID": 400959},
    {"schoolName": "Datamex Institute of Computer Technology", "city": "Caloocan City", "schoolID": 400960},
    {"schoolName": "Informatics College", "city": "Caloocan City", "schoolID": 400962},
    {"schoolName": "Lady of Lourdes Hospital and Colleges of Caybiga", "city": "Caloocan City", "schoolID": 400967},
    {"schoolName": "Martinez Memorial Colleges", "city": "Caloocan City", "schoolID": 400972},
    {"schoolName": "STI College", "city": "Caloocan City", "schoolID": 400978},
    {"schoolName": "APEC Schools", "city": "Caloocan City", "schoolID": 405581},
    {"schoolName": "Anchor of Life Academy", "city": "Caloocan City", "schoolID": 406674},
    {"schoolName": "Divine Mercy College Foundation", "city": "Caloocan City", "schoolID": 406677},
    {"schoolName": "La Consolacion College", "city": "Caloocan City", "schoolID": 406678},
    {"schoolName": "Notre Dame of Greater Manila", "city": "Caloocan City", "schoolID": 406681},
    {"schoolName": "Philippine Cultural College", "city": "Caloocan City", "schoolID": 406683},
    {"schoolName": "St. Mary's Academy", "city": "Caloocan City", "schoolID": 406685},
    {"schoolName": "Systems Plus Computer College", "city": "Caloocan City", "schoolID": 406686},
    {"schoolName": "Baesa Adventist Academy", "city": "Caloocan City", "schoolID": 406688},
    {"schoolName": "World Citi Colleges-Caloocan", "city": "Caloocan City", "schoolID": 406691},
    {"schoolName": "Manila Central University", "city": "Caloocan City", "schoolID": 406696},
    {"schoolName": "St. Dominic Savio College", "city": "Caloocan City", "schoolID": 406698},
    {"schoolName": "Holy Redeemer School", "city": "Caloocan City", "schoolID": 406711},
    {"schoolName": "Mystical Rose School of Caloocan", "city": "Caloocan City", "schoolID": 406713},
    {"schoolName": "St. Clare College of Caloocan", "city": "Caloocan City", "schoolID": 406715},
    {"schoolName": "Immaculada Concepcion Colleges", "city": "Caloocan City", "schoolID": 406726},
    {"schoolName": "St. Joseph College of Novaliches", "city": "Caloocan City", "schoolID": 406729},
    {"schoolName": "Guardian Angel School", "city": "Caloocan City", "schoolID": 406732},
    {"schoolName": "Holy Infant Montessori Center", "city": "Caloocan City", "schoolID": 406733},
    {"schoolName": "La Consolacion College", "city": "Caloocan City", "schoolID": 406734},
    {"schoolName": "Rosary Hills International School", "city": "Caloocan City", "schoolID": 406736},
    {"schoolName": "St. Benedict School of Novaliches", "city": "Caloocan City", "schoolID": 406740},
    {"schoolName": "St. Therese of Rose School", "city": "Caloocan City", "schoolID": 406745},
    {"schoolName": "The Immaculate Mother Academy", "city": "Caloocan City", "schoolID": 406747},
    {"schoolName": "Interface Computer College", "city": "Caloocan City", "schoolID": 407463},
    {"schoolName": "Regina Coeli Education Centre Foundation", "city": "Caloocan City", "schoolID": 483507},
    {"schoolName": "St. John Academy", "city": "Caloocan City", "schoolID": 483508},
    {"schoolName": "E.M. Castro Educational Foundation", "city": "Caloocan City", "schoolID": 483512},
    {"schoolName": "St. Mary Goretti School", "city": "Caloocan City", "schoolID": 483517},
    {"schoolName": "Pledge of Love School", "city": "Caloocan City", "schoolID": 483519},
    {"schoolName": "St. Vincent de Ferrer College of Camarin", "city": "Caloocan City", "schoolID": 483521},
    {"schoolName": "Young Achievers School", "city": "Caloocan City", "schoolID": 483526},
    {"schoolName": "Golden Link College Foundation", "city": "Caloocan City", "schoolID": 483528},
    {"schoolName": "Genesis Christian Academy", "city": "Caloocan City", "schoolID": 483540},
    {"schoolName": "Mother of Divine Grace Academy", "city": "Caloocan City", "schoolID": 483541},
    {"schoolName": "Holy Angel School", "city": "Caloocan City", "schoolID": 483545},
    {"schoolName": "Escuela de Sophia", "city": "Caloocan City", "schoolID": 483548},
    {"schoolName": "Knowledgeville School of Excellence", "city": "Caloocan City", "schoolID": 483550},
    {"schoolName": "Our Lord's Angels School", "city": "Caloocan City", "schoolID": 483551},
    {"schoolName": "Escuela San Gabriel De Arcangel Foundation", "city": "Caloocan City", "schoolID": 483552},
    {"schoolName": "University of the East", "city": "Caloocan City", "schoolID": 483559},
    {"schoolName": "Christ Jeross Christian Academy", "city": "Caloocan City", "schoolID": 483568},
    {"schoolName": "Ridgewood School", "city": "Caloocan City", "schoolID": 483569},
    {"schoolName": "Academy of Saint Andrew", "city": "Caloocan City", "schoolID": 483570},
    {"schoolName": "Sagrada Familia School", "city": "Caloocan City", "schoolID": 483587},
    {"schoolName": "Our Lady of Grace School", "city": "Caloocan City", "schoolID": 483653},
    {"schoolName": "University of Caloocan City", "city": "Caloocan City", "schoolID": 600199},
    {"schoolName": "Northern Rizal Yorklin School", "city": "Caloocan City", "schoolID": 1406680},
    {"schoolName": "St. Therese of the Child Jesus Jesus Kidz Academy", "city": "Caloocan City", "schoolID": 407189},
    {"schoolName": "ABE International College of Business and Economics", "city": "Las Piñas City", "schoolID": 400981},
    {"schoolName": "AMA Computer College", "city": "Las Piñas City", "schoolID": 400986},
    {"schoolName": "Southville International School and Colleges", "city": "Las Piñas City", "schoolID": 400997},
    {"schoolName": "St. Augustine College", "city": "Las Piñas City", "schoolID": 400999},
    {"schoolName": "STI College", "city": "Las Piñas City", "schoolID": 401000},
    {"schoolName": "AMA Basic Education", "city": "Las Piñas City", "schoolID": 405614},
    {"schoolName": "Southville International School Affiliated with Foreign Universities", "city": "Las Piñas City", "schoolID": 405660},
    {"schoolName": "Philippine Merchant Marine School", "city": "Las Piñas City", "schoolID": 407036},
    {"schoolName": "Young Achievers International School", "city": "Las Piñas City", "schoolID": 407078},
    {"schoolName": "Bernardo College", "city": "Las Piñas City", "schoolID": 407079},
    {"schoolName": "Camella School", "city": "Las Piñas City", "schoolID": 407082},
    {"schoolName": "Divine Light Academy", "city": "Las Piñas City", "schoolID": 407085},
    {"schoolName": "Holy Rosary Academy", "city": "Las Piñas City", "schoolID": 407087},
    {"schoolName": "Brittany School", "city": "Las Piñas City", "schoolID": 407090},
    {"schoolName": "St. Mark's Institute", "city": "Las Piñas City", "schoolID": 407104},
    {"schoolName": "St. Michael's School", "city": "Las Piñas City", "schoolID": 407105},
    {"schoolName": "Saint Therese School", "city": "Las Piñas City", "schoolID": 407106},
    {"schoolName": "University of Perpetual Help System Dalta", "city": "Las Piñas City", "schoolID": 407107},
    {"schoolName": "Westfield Science", "city": "Las Piñas City", "schoolID": 407109},
    {"schoolName": "Augustinian Abbey School", "city": "Las Piñas City", "schoolID": 407110},
    {"schoolName": "Blessed Trinity School", "city": "Las Piñas City", "schoolID": 407113},
    {"schoolName": "Bloomfield Academy", "city": "Las Piñas City", "schoolID": 407114},
    {"schoolName": "Creative Middle School", "city": "Las Piñas City", "schoolID": 407115},
    {"schoolName": "Don Carlo Cavina School", "city": "Las Piñas City", "schoolID": 407117},
    {"schoolName": "Elizabeth Seton School", "city": "Las Piñas City", "schoolID": 407119},
    {"schoolName": "Las Piñas College", "city": "Las Piñas City", "schoolID": 407124},
    {"schoolName": "Montessori de Manila", "city": "Las Piñas City", "schoolID": 407131},
    {"schoolName": "Our Lady of Pilar Montessori Center", "city": "Las Piñas City", "schoolID": 407134},
    {"schoolName": "Saint Francis of Assisi College", "city": "Las Piñas City", "schoolID": 407142},
    {"schoolName": "Sto. Niño De Eucharistia Academy", "city": "Las Piñas City", "schoolID": 407146},
    {"schoolName": "APEC Schools", "city": "Las Piñas City", "schoolID": 407447},
    {"schoolName": "Schola de Vita", "city": "Las Piñas City", "schoolID": 486522},
    {"schoolName": "GCF South Metro Christian School", "city": "Las Piñas City", "schoolID": 486534},
    {"schoolName": "ABE International Business College", "city": "Makati City", "schoolID": 401015},
    {"schoolName": "AMA Computer College", "city": "Las Piñas City", "schoolID": 401016},
    {"schoolName": "AMA Computer Learning Center", "city": "Makati City", "schoolID": 401027},
    {"schoolName": "Asia Pacific College", "city": "Makati City", "schoolID": 401034},
    {"schoolName": "Centro Escolar University", "city": "Makati City", "schoolID": 401059},
    {"schoolName": "iACADEMY", "city": "Makati City", "schoolID": 401067},
    {"schoolName": "STI College", "city": "Makati City", "schoolID": 401074},
    {"schoolName": "Global City Innovative College", "city": "Makati City", "schoolID": 401670},
    {"schoolName": "Asian Institute of Computer Studies", "city": "Makati City", "schoolID": 405667},
    {"schoolName": "St. Paul College", "city": "Makati City", "schoolID": 406821},
    {"schoolName": "Assumption College", "city": "Makati City", "schoolID": 406836},
    {"schoolName": "Don Bosco Technical Institute", "city": "Makati City", "schoolID": 406837},
    {"schoolName": "Colegio de Sta. Rosa", "city": "Makati City", "schoolID": 406844},
    {"schoolName": "Colegio San Agustin", "city": "Makati City", "schoolID": 406851},
    {"schoolName": "Guadalupe Catholic School", "city": "Makati City", "schoolID": 406855},
    {"schoolName": "Makati Hope Christian School", "city": "Makati City", "schoolID": 406858},
    {"schoolName": "Bethany Baptist Academy", "city": "Makati City", "schoolID": 406864},
    {"schoolName": "Light of the World Christian Academy", "city": "Makati City", "schoolID": 485008},
    {"schoolName": "Bloomfield Academy", "city": "Makati City", "schoolID": 485013},
    {"schoolName": "Reach International School", "city": "Makati City", "schoolID": 485032},
    {"schoolName": "University of Makati", "city": "Makati City", "schoolID": 600305},
    {"schoolName": "City of Malabon University", "city": "Malabon City", "schoolID": 407094},
    {"schoolName": "Philippine Malabon Cultural Institute", "city": "Malabon City", "schoolID": 407209},
    {"schoolName": "St. James Academy", "city": "Malabon City", "schoolID": 407210},
    {"schoolName": "St. Therese of the Child Jesus Academy", "city": "Malabon City", "schoolID": 407211},
    {"schoolName": "Immaculate Conception Parochial School", "city": "Malabon City", "schoolID": 407215},
    {"schoolName": "De La Salle Araneta University", "city": "Malabon City", "schoolID": 407220},
    {"schoolName": "Salvador Araneta Memorial Institute", "city": "Malabon City", "schoolID": 407223},
    {"schoolName": "Probex School", "city": "Malabon City", "schoolID": 487514},
    {"schoolName": "Arellano University", "city": "Malabon City", "schoolID": 487518},
    {"schoolName": "ABE International College of Business and Accountancy", "city": "Malate", "schoolID": 401135},
    {"schoolName": "De La Salle University", "city": "Malate", "schoolID": 401151},
    {"schoolName": "Emilio Aguinaldo College", "city": "Malate", "schoolID": 401160},
    {"schoolName": "Lyceum of the Philippines University", "city": "Malate", "schoolID": 401188},
    {"schoolName": "Mapua Institute of Technology", "city": "Malate", "schoolID": 401193},
    {"schoolName": "St. Paul University", "city": "Malate", "schoolID": 401293},
    {"schoolName": "STI College", "city": "Malate", "schoolID": 401303},
    {"schoolName": "Adamson University", "city": "Malate", "schoolID": 406359},
    {"schoolName": "Colegio de San Juan de Letran", "city": "Malate", "schoolID": 406360},
    {"schoolName": "Ermita Catholic School", "city": "Malate", "schoolID": 406363},
    {"schoolName": "Jesus Reigns Christian Academy", "city": "Malate", "schoolID": 406364},
    {"schoolName": "Malate Catholic School", "city": "Malate", "schoolID": 406366},
    {"schoolName": "Philippine Christian University", "city": "Malate", "schoolID": 406367},
    {"schoolName": "St. Anthony School", "city": "Malate", "schoolID": 406370},
    {"schoolName": "St. Scholastica's College", "city": "Malate", "schoolID": 406371},
    {"schoolName": "Santa Isabel College", "city": "Malate", "schoolID": 406372},
    {"schoolName": "Colegio de Sta. Rosa", "city": "Malate", "schoolID": 407466},
    {"schoolName": "Colegio de Sta. Rosa", "city": "Malate", "schoolID": 407466},
    {"schoolName": "Pamantasan ng Lungsod ng Maynila", "city": "Malate", "schoolID": 600201},
    {"schoolName": "AMA Computer College", "city": "Mandaluyong City", "schoolID": 401091},
    {"schoolName": "Our Lady of Guadalupe Colleges", "city": "Mandaluyong City", "schoolID": 401114},
    {"schoolName": "St. Augustine School of Nursing", "city": "Mandaluyong City", "schoolID": 401132},
    {"schoolName": "STI College", "city": "Mandaluyong City", "schoolID": 401134},
    {"schoolName": "Don Bosco Technical College", "city": "Mandaluyong City", "schoolID": 406749},
    {"schoolName": "Good Shepherd Christian School", "city": "Mandaluyong City", "schoolID": 406750},
    {"schoolName": "Arellano University", "city": "Mandaluyong City", "schoolID": 406753},
    {"schoolName": "International Baptist College", "city": "Mandaluyong City", "schoolID": 406756},
    {"schoolName": "Jose Rizal University", "city": "Mandaluyong City", "schoolID": 406757},
    {"schoolName": "La Salle-Green Hills", "city": "Mandaluyong City", "schoolID": 406758},
    {"schoolName": "Lourdes School", "city": "Mandaluyong City", "schoolID": 406760},
    {"schoolName": "Saint John Bosco Institute of Arts and Sciences", "city": "Mandaluyong City", "schoolID": 407284},
    {"schoolName": "La Salle Green Hills Adult Night High School", "city": "Mandaluyong City", "schoolID": 484014},
    {"schoolName": "Key School Manila", "city": "Mandaluyong City", "schoolID": 484019},
    {"schoolName": "Rizal Technological University", "city": "Mandaluyong City", "schoolID": 600110},
    {"schoolName": "Centro Escolar University", "city": "Manila City", "schoolID": 401150},
    {"schoolName": "Don Bosco School", "city": "Manila City", "schoolID": 406351},
    {"schoolName": "De Ocampo Memorial College", "city": "Manila City", "schoolID": 407627},
    {"schoolName": "College of the Holy Spirit", "city": "Manila City", "schoolID": 482043},
    {"schoolName": "Universidad de Manila", "city": "Manila City", "schoolID": 600200},
    {"schoolName": "AMA Computer Learning Center", "city": "Marikina City", "schoolID": 401327},
    {"schoolName": "STI College", "city": "Marikina City", "schoolID": 401329},
    {"schoolName": "Berean Crosspointe International", "city": "Marikina City", "schoolID": 405685},
    {"schoolName": "Pamantasan ng Lungsod ng Marikina", "city": "Marikina City", "schoolID": 406069},
    {"schoolName": "Jesus' Flock Academy", "city": "Marikina City", "schoolID": 406766},
    {"schoolName": "Marikina Catholic School", "city": "Marikina City", "schoolID": 406768},
    {"schoolName": "Nuestra Señora De Guia Academy", "city": "Marikina City", "schoolID": 406773},
    {"schoolName": "Roosevelt College", "city": "Marikina City", "schoolID": 406779},
    {"schoolName": "Celestial Village Academy", "city": "Marikina City", "schoolID": 406783},
    {"schoolName": "Infant Jesus Academy", "city": "Marikina City", "schoolID": 406787},
    {"schoolName": "Ingenium School", "city": "Marikina City", "schoolID": 406788},
    {"schoolName": "Jehoshua Christian School", "city": "Marikina City", "schoolID": 406789},
    {"schoolName": "Marist School", "city": "Marikina City", "schoolID": 406798},
    {"schoolName": "National Christian Life College", "city": "Marikina City", "schoolID": 406807},
    {"schoolName": "Our Lady of Perpetual Succor College", "city": "Marikina City", "schoolID": 406808},
    {"schoolName": "Redeemed in Christ School", "city": "Marikina City", "schoolID": 406811},
    {"schoolName": "St. Nicholas School", "city": "Marikina City", "schoolID": 406814},
    {"schoolName": "College of Arts and Sciences of Asia & the Pacific", "city": "Marikina City", "schoolID": 407270},
    {"schoolName": "APEC Schools Concepcion Dos", "city": "Marikina City", "schoolID": 407373},
    {"schoolName": "St. Scholastica's Academy", "city": "Marikina City", "schoolID": 407467},
    {"schoolName": "San Lorenzo Ruiz de Manila School", "city": "Marikina City", "schoolID": 484519},
    {"schoolName": "Irvinghall School", "city": "Marikina City", "schoolID": 484530},
    {"schoolName": "APEC Schools Concepcion Uno", "city": "Marikina City", "schoolID": 484569},
    {"schoolName": "AFFORDABLE PRIVATE EDUCATION CENTER", "city": "Marikina City", "schoolID": 484570},
    {"schoolName": "Informatics College Northgate", "city": "Muntinlupa City", "schoolID": 401332},
    {"schoolName": "Informatics Computer Institute", "city": "Muntinlupa City", "schoolID": 401337},
    {"schoolName": "Marianum College", "city": "Muntinlupa City", "schoolID": 401340},
    {"schoolName": "STI College", "city": "Muntinlupa City", "schoolID": 401360},
    {"schoolName": "Christ the King College of Science and Technology", "city": "Muntinlupa City", "schoolID": 401369},
    {"schoolName": "Facilities Management College", "city": "Muntinlupa City", "schoolID": 401372},
    {"schoolName": "Westbay College", "city": "Muntinlupa City", "schoolID": 401377},
    {"schoolName": "APEC Schools", "city": "Muntinlupa City", "schoolID": 405688},
    {"schoolName": "International Electronics and Technical Institute College", "city": "Muntinlupa City", "schoolID": 405691},
    {"schoolName": "AMA Computer Learning Center of Muntinlupa", "city": "Muntinlupa City", "schoolID": 406414},
    {"schoolName": "Colegio Dela Nuestra Señora", "city": "Muntinlupa City", "schoolID": 407311},
    {"schoolName": "Living Light Academy", "city": "Muntinlupa City", "schoolID": 407321},
    {"schoolName": "Muntinlupa Cosmopolitan School", "city": "Muntinlupa City", "schoolID": 407328},
]

let parentDiv = document.getElementById('data');

for (let index = 0; index < data.length; index++) {
  let div = document.createElement('div');
  div.className = 'schoolcard';

  let h1 = document.createElement('h1');
  h1.className = 'schoolname';
  h1.innerHTML = data[index].schoolName;

  let addr = document.createElement('p');
  addr.className = 'schooladdr'
  addr.innerHTML = data[index].city;

  let id = document.createElement('p');
  id.className = 'schoolid'
  id.innerHTML = data[index].schoolID;

  div.appendChild(h1);
  div.appendChild(addr);
  div.appendChild(id);
  parentDiv.appendChild(div);
}