let data = [
    {"schoolName": "ABE International Business College", "city": "Caloocan City", "schoolID": 400942},
    {"schoolName": "AMA Computer College", "city": "Caloocan City", "schoolID": 400947},
    {"schoolName": "AMA Computer Learning Center", "city": "Caloocan City", "schoolID": 400951},
    {"schoolName": "Asian Institue of Computer Studies", "city": "Caloocan City", "schoolID": 400952},
    {"schoolName": "Colegio de San Gabriel Arcangel", "city": "Caloocan City", "schoolID": 400959},
    {"schoolName": "Datamex Institute of Computer Technology", "city": "Caloocan City", "schoolID": 400960},
    {"schoolName": "Informatics College", "city": "Caloocan City", "schoolID": 400962},
    {"schoolName": "Lady of Lourdes Hospital and Colleges of Caybiga", "city": "Caloocan City", "schoolID": 400967},
    {"schoolName": "Martinez Memorial Colleges", "city": "Caloocan City", "schoolID": 400972},
    {"schoolName": "STI College", "city": "Caloocan City", "schoolID": 400978},
    {"schoolName": "Access Computer and Technical College - Camarin Campus", "city": "Caloocan City", "schoolID": 405537},
    {"schoolName": "Access Computer and Technical College - Monumento Campus", "city": "Caloocan City", "schoolID": 405537},
    {"schoolName": "Asian Caregiving and Technology Education Centers", "city": "Caloocan City", "schoolID": 405583},
    {"schoolName": "Emmanuel John Institute of Science & Technology", "city": "Caloocan City", "schoolID": 405602},
    {"schoolName": "Lorraine Technical School", "city": "Caloocan City", "schoolID": 405359},
    {"schoolName": "Divine Mercy College Foundation", "city": "Caloocan City", "schoolID": 406677},
    {"schoolName": "La Consolacion College", "city": "Caloocan City", "schoolID": 406678},
    {"schoolName": "Notre Dame of Greater Manila", "city": "Caloocan City", "schoolID": 406681},
    {"schoolName": "St. Mary's Academy", "city": "Caloocan City", "schoolID": 406685},
    {"schoolName": "Systems Plus Computer College", "city": "Caloocan City", "schoolID": 406686},
    {"schoolName": "Baesa Adventist Academy", "city": "Caloocan City", "schoolID": 406688},
    {"schoolName": "World Citi Colleges", "city": "Caloocan City", "schoolID": 406691},
    {"schoolName": "Manila Central University", "city": "Caloocan City", "schoolID": 406696},
    {"schoolName": "Maranatha Christian Academy", "city": "Caloocan City", "schoolID": 406712},
    {"schoolName": "Mystical Rose School", "city": "Caloocan City", "schoolID": 406713},
    {"schoolName": "Newland Center for Education", "city": "Caloocan City", "schoolID": 406714},
    {"schoolName": "St. Clare College", "city": "Caloocan City", "schoolID": 406717},
    {"schoolName": "Immaculada Concepcion Colleges", "city": "Caloocan City", "schoolID": 406729},
    {"schoolName": "La Consolacion College - Novaliches", "city": "Caloocan City", "schoolID": 406734},
    {"schoolName": "Rosary Hills International School", "city": "Caloocan City", "schoolID": 406735},
    {"schoolName": "The Immaculate Mother Academy", "city": "Caloocan City", "schoolID": 406747},
    {"schoolName": "Cieverose College", "city": "Caloocan City", "schoolID": 407034},
    {"schoolName": "St. Francis Technical Institute for Development, Training and Competency Assessment", "city": "Caloocan City", "schoolID": 407449},
    {"schoolName": "Interface Computer College", "city": "Caloocan City", "schoolID": 407463},
    {"schoolName": "St. Agnes Academy of Caloocan", "city": "Caloocan City", "schoolID": 483505},
    {"schoolName": "Regina Coeli Education Centre Foundation", "city": "Caloocan City", "schoolID": 483507},
    {"schoolName": "Dr. Rosita B. Britanico", "city": "Caloocan City", "schoolID": 483510},
    {"schoolName": "E.M. Castro", "city": "Caloocan City", "schoolID": 483512},
    {"schoolName": "St. Mary Goretti School", "city": "Caloocan City", "schoolID": 483517},
    {"schoolName": "St. Vincent de Ferrer College", "city": "Caloocan City", "schoolID": 483521},
    {"schoolName": "Young Achievers' School", "city": "Caloocan City", "schoolID": 483526},
    {"schoolName": "Golden Link College", "city": "Caloocan City", "schoolID": 483528},
    {"schoolName": "Mother of Divine Grace Academy", "city": "Caloocan City", "schoolID": 483541},
    {"schoolName": "Escuela de Sophia", "city": "Caloocan City", "schoolID": 483548},
    {"schoolName": "Escuela San Gabriel De Arcangel Foundation", "city": "Caloocan City", "schoolID": 483552},
    {"schoolName": "Rhexane Academy", "city": "Caloocan City", "schoolID": 483558},
    {"schoolName": "University of the East", "city": "Caloocan City", "schoolID": 483559},
    {"schoolName": "Ridgewood School", "city": "Caloocan City", "schoolID": 483569},
    {"schoolName": "St. Vincent Institute of Technology", "city": "Caloocan City", "schoolID": 483620},
    {"schoolName": "Our Lady of Grace School", "city": "Caloocan City", "schoolID": 483653},
    {"schoolName": "Northern Rizal Yorklin School", "city": "Caloocan City", "schoolID": 406680},
    {"schoolName": "Montessori Professional College", "city": "Caloocan City", "schoolID": 407302},
    {"schoolName": "AMA Computer Learning Center", "city": "Las Piñas City", "schoolID": 400988},
    {"schoolName": "ABE International College of Business and Economics", "city": "Las Piñas City", "schoolID": 400981},
    {"schoolName": "AMA Computer College", "city": "Las Piñas City", "schoolID": 400986},
    {"schoolName": "St. Augustine College", "city": "Las Piñas City", "schoolID": 400999},
    {"schoolName": "SSTI College", "city": "Las Piñas City", "schoolID": 401000},
    {"schoolName": "AMA Basic Education of Las Piñas City", "city": "Las Piñas City", "schoolID": 405614},
    {"schoolName": "Dr. Filemon C. Aguilar Information Technology Training Institute", "city": "Las Piñas City", "schoolID": 405630},
    {"schoolName": "International Electronics and Technical Institute", "city": "Las Piñas City", "schoolID": 405657},
    {"schoolName": "Southville International School Affiliated with Foreign Universities", "city": "Las Piñas City", "schoolID": 405660},
    {"schoolName": "AZGH College", "city": "Las Piñas City", "schoolID": 405952},
    {"schoolName": "Datamex Institute of Computer Technology", "city": "Las Piñas City", "schoolID": 406276},
    {"schoolName": "Asian Caregiving and Technology Education Centers", "city": "Las Piñas City", "schoolID": 406499},
    {"schoolName": "Young Achievers International School", "city": "Las Piñas City", "schoolID": 407078},
    {"schoolName": "Bernardo College", "city": "Las Piñas City", "schoolID": 407079},
    {"schoolName": "St. Joseph's Academy", "city": "Las Piñas City", "schoolID": 407103},
    {"schoolName": "Saint Therese School", "city": "Las Piñas City", "schoolID": 407106},
    {"schoolName": "University of Perpetual Help System Dalta", "city": "Las Piñas City", "schoolID": 407107},
    {"schoolName": "Don Carlo Cavina School", "city": "Las Piñas City", "schoolID": 407117},
    {"schoolName": "Mary Immaculate Parish Special School", "city": "Las Piñas City", "schoolID": 407127},
    {"schoolName": "Montessori de Manila", "city": "Las Piñas City", "schoolID": 407131},
    {"schoolName": "Saint Francis of Assisi College", "city": "Las Piñas City", "schoolID": 407142},
    {"schoolName": "Seed Academy", "city": "Las Piñas City", "schoolID": 407371},
    {"schoolName": "ABE International Business College", "city": "Makati City", "schoolID": 401015},
    {"schoolName": "AMA Computer College", "city": "Makati City", "schoolID": 401016},
    {"schoolName": "AMA Computer Learning Center of Guadalupe", "city": "Makati City", "schoolID": 401027},
    {"schoolName": "Career Academy Asia- PHINMA Education", "city": "Makati City", "schoolID": 401056},
    {"schoolName": "iACADEMY, Belair", "city": "Makati City", "schoolID": 401067},
    {"schoolName": "Infotech Institute of Arts and Sciences", "city": "Makati City", "schoolID": 401071},
    {"schoolName": "STI College", "city": "Makati City", "schoolID": 401074},
    {"schoolName": "Global City Innovative College", "city": "Makati City", "schoolID": 401670},
    {"schoolName": "Asian Institute of Computer Studies", "city": "Makati City", "schoolID": 405667},
    {"schoolName": "International Academy of Management and Economics", "city": "Makati City", "schoolID": 406398},
    {"schoolName": "St. Paul College", "city": "Makati City", "schoolID": 406821},
    {"schoolName": "Don Bosco Technical Institute", "city": "Makati City", "schoolID": 406837},
    {"schoolName": "International Electronics and Technical Institute", "city": "Makati City", "schoolID": 406841},
    {"schoolName": "St. Mary of the Woods School", "city": "Makati City", "schoolID": 406863},
    {"schoolName": "Saint John Bosco Institute of Arts and Sciences - Pio del Pilar", "city": "Makati City", "schoolID": 407054},
    {"schoolName": "Saint John Bosco Institute of Arts and Sciences - Makati City", "city": "Makati City", "schoolID": 407058},
    {"schoolName": "Montessori Professional College", "city": "Makati City", "schoolID": 407453},
    {"schoolName": "University of Makati", "city": "Makati City", "schoolID": 600305},
    {"schoolName": "St. Catherine Institute of Technology", "city": "Malabon City", "schoolID": 405668},
    {"schoolName": "City of Malabon Polytechnic Institute", "city": "Malabon City", "schoolID": 406403},
    {"schoolName": "College of Saint Amatiel", "city": "Malabon City", "schoolID": 406404},
    {"schoolName": "St. Therese of the Child Jesus Academy", "city": "Malabon City", "schoolID": 407211},
    {"schoolName": "Immaculate Conception Parochial School", "city": "Malabon City", "schoolID": 407215},
    {"schoolName": "De La Salle Araneta University", "city": "Malabon City", "schoolID": 407220},
    {"schoolName": "Arellano University", "city": "Malabon City", "schoolID": 487518},
    {"schoolName": "ABE International College of Business and Accountancy", "city": "Malate", "schoolID": 401135},
    {"schoolName": "Emilio Aguinaldo College", "city": "Malate", "schoolID": 401160},
    {"schoolName": "Lyceum of the Philippines University", "city": "Malate", "schoolID": 401188},
    {"schoolName": "Mapua Institute of Technology", "city": "Malate", "schoolID": 401193},
    {"schoolName": "Philippine College of Health Sciences", "city": "Malate", "schoolID": 401242},
    {"schoolName": "St. Paul University", "city": "Malate", "schoolID": 401293},
    {"schoolName": "STI College", "city": "Malate", "schoolID": 401303},
    {"schoolName": "Industrial Advancement Academy of the Philippines", "city": "Malate", "schoolID": 405684},
    {"schoolName": "Colegio de San Juan de Letran", "city": "Malate", "schoolID": 406360},
    {"schoolName": "Ermita Catholic School", "city": "Malate", "schoolID": 406363},
    {"schoolName": "Malate Catholic School", "city": "Malate", "schoolID": 406366},
    {"schoolName": "Philippine Christian University", "city": "Malate", "schoolID": 406367},
    {"schoolName": "Philippine Women's University", "city": "Malate", "schoolID": 406368},
    {"schoolName": "St. Anthony School", "city": "Malate", "schoolID": 406370},
    {"schoolName": "St. Scholastica's College", "city": "Malate", "schoolID": 406371},
    {"schoolName": "Technological University of the Philippines", "city": "Malate", "schoolID": 600202},
    {"schoolName": "AMA Computer College", "city": "Mandaluyong City", "schoolID": 401091},
    {"schoolName": "Our Lady of Guadalupe Colleges", "city": "Mandaluyong City", "schoolID": 401114},
    {"schoolName": "St. Augustine School of Nursing", "city": "Mandaluyong City", "schoolID": 401132},
    {"schoolName": "STI College", "city": "Mandaluyong City", "schoolID": 401134},
    {"schoolName": "International Training Center and Hospitality Institute", "city": "Mandaluyong City", "schoolID": 405670},
    {"schoolName": "Arellano University", "city": "Mandaluyong City", "schoolID": 406753},
    {"schoolName": "San Felipe Neri Parochial School", "city": "Mandaluyong City", "schoolID": 406754},
    {"schoolName": "International Baptist College", "city": "Mandaluyong City", "schoolID": 406756},
    {"schoolName": "Jose Rizal University", "city": "Mandaluyong City", "schoolID": 406757},
    {"schoolName": "Saint John Bosco Institute of Arts and Sciences", "city": "Mandaluyong City", "schoolID": 407284},
    {"schoolName": "Gateways Institute of Science and Technology", "city": "Mandaluyong City", "schoolID": 407372},
    {"schoolName": "La Salle Green Hills Adult Night High School", "city": "Mandaluyong City", "schoolID": 484014},
    {"schoolName": "Rizal Technological University", "city": "Mandaluyong City", "schoolID": 600110},
    {"schoolName": "Montessori Professional College", "city": "Manila City", "schoolID": 407454},
    {"schoolName": "Centro Escolar University", "city": "Manila City", "schoolID": 401150},
    {"schoolName": "De Ocampo Memorial College", "city": "Manila City", "schoolID": 407627},
    {"schoolName": "College of the Holy Spirit", "city": "Manila City", "schoolID": 482043},
    {"schoolName": "Universidad de Manila", "city": "Manila City", "schoolID": 600200},
    {"schoolName": "AMA Computer Learning Center", "city": "Marikina City", "schoolID": 401327},
    {"schoolName": "St. Chamuel Institute of Technology", "city": "Marikina City", "schoolID": 401328},
    {"schoolName": "STI College", "city": "Marikina City", "schoolID": 401329},
    {"schoolName": "IETI College of Science and Technology", "city": "Marikina City", "schoolID": 405687},
    {"schoolName": "Nuestra Señora De Guia Academy", "city": "Marikina City", "schoolID": 406773},
    {"schoolName": "Celestial Village Academy", "city": "Marikina City", "schoolID": 406783},
    {"schoolName": "Marist School", "city": "Marikina City", "schoolID": 406798},
    {"schoolName": "MSH Sisters Academy", "city": "Marikina City", "schoolID": 406806},
    {"schoolName": "National Christian Life College", "city": "Marikina City", "schoolID": 406807},
    {"schoolName": "Our Lady of Perpetual Succor College", "city": "Marikina City", "schoolID": 406808},
    {"schoolName": "College of Arts and Sciences of Asia & the Pacific", "city": "Marikina City", "schoolID": 407270},
    {"schoolName": "Montessori Professional College", "city": "Marikina City", "schoolID": 407455},
    {"schoolName": "Gentle Angels School", "city": "Marikina City", "schoolID": 484513},
    {"schoolName": "San Lorenzo Ruiz de Manila School", "city": "Marikina City", "schoolID": 484519},
    {"schoolName": "Irvinghall School", "city": "Marikina City", "schoolID": 484530},
    {"schoolName": "Marikina Polytechnic College", "city": "Marikina City", "schoolID": 600204},
    {"schoolName": "Informatics College Northgate", "city": "Muntinlupa City", "schoolID": 401332},
    {"schoolName": "STI College", "city": "Muntinlupa City", "schoolID": 401360},
    {"schoolName": "Christ the King College of Science and Technology", "city": "Muntinlupa City", "schoolID": 401369},
    {"schoolName": "Facilities Management College", "city": "Muntinlupa City", "schoolID": 401372},
    {"schoolName": "Facilities Westbay College", "city": "Muntinlupa City", "schoolID": 401377},
    {"schoolName": "International Electronics and Technical Institute College", "city": "Muntinlupa City", "schoolID": 405691},
    {"schoolName": "Datamex Institute of Computer Technology", "city": "Muntinlupa City", "schoolID": 406277},
    {"schoolName": "AMA Computer Learning Center", "city": "Muntinlupa City", "schoolID": 406414},
    {"schoolName": "Colegio Dela Nuestra Señora De Guadalupe", "city": "Muntinlupa City", "schoolID": 407311},
    {"schoolName": "Br. Rafael Donato FSC Night High School", "city": "Muntinlupa City", "schoolID": 407350},
    {"schoolName": "Our Lady of the Lake School", "city": "Muntinlupa City", "schoolID": 407350},
    {"schoolName": "Our Lady of the Lake School", "city": "Muntinlupa City", "schoolID": 407357},
    {"schoolName": "San Roque Catholic School", "city": "Muntinlupa City", "schoolID": 407362},
    {"schoolName": "San Beda College Alabang", "city": "Muntinlupa City", "schoolID": 407364},
    {"schoolName": "Saint Bernadette College", "city": "Muntinlupa City", "schoolID": 407365},
    {"schoolName": "EJIST-VALENZUELA", "city": "Muntinlupa City", "schoolID": 407374},
    {"schoolName": "Lakewood School of Alabang", "city": "Muntinlupa City", "schoolID": 486545},
    {"schoolName": "South Mansfield College", "city": "Muntinlupa City", "schoolID": 488528},
    {"schoolName": "Lyceum of Alabang", "city": "Muntinlupa City", "schoolID": 488551},
    {"schoolName": "Philippine Welding Technology Skills and Services Center", "city": "Navotas City", "schoolID": 405692},
    {"schoolName": "Concordia College", "city": "Paco", "schoolID": 406377},
    {"schoolName": "AMA Computer Learning Center", "city": "Paco", "schoolID": 406506},
    {"schoolName": "St. Joseph School", "city": "Pandacan", "schoolID": 406376},
    {"schoolName": "ERDA Technical and Vocational Secondary School", "city": "Pandacan", "schoolID": 482020},
    {"schoolName": "AMA Computer College", "city": "Parañaque City", "schoolID": 401383},
    {"schoolName": "Asian Institute of Computer Studies", "city": "Parañaque City", "schoolID": 401387},
    {"schoolName": "Immaculate Heart of Mary College", "city": "Parañaque City", "schoolID": 401390},
    {"schoolName": "STI College", "city": "Parañaque City", "schoolID": 401402},
    {"schoolName": "Universal Colleges of Parañaque", "city": "Parañaque City", "schoolID": 401405},
    {"schoolName": "Datamex Institute of Computer Technology", "city": "Parañaque City", "schoolID": 405697},
    {"schoolName": "Go Tec International Business School", "city": "Parañaque City", "schoolID": 405698},
    {"schoolName": "Premiere Computer Learning Center", "city": "Parañaque City", "schoolID": 405700},
    {"schoolName": "Sapphire International Aviation Academy", "city": "Parañaque City", "schoolID": 406283},
    {"schoolName": "Infotech College Institute of Arts and Sciences", "city": "Parañaque City", "schoolID": 406872},
    {"schoolName": "Ann Arbor Montessori Learning Center", "city": "Parañaque City", "schoolID": 406875},
    {"schoolName": "Young Masters Academy", "city": "Parañaque City", "schoolID": 406972},
    {"schoolName": "Arandia College", "city": "Parañaque City", "schoolID": 406973},
    {"schoolName": "Marymount School", "city": "Parañaque City", "schoolID": 406983},
    {"schoolName": "Shekinah Christian Training Center", "city": "Parañaque City", "schoolID": 406998},
    {"schoolName": "Kid's Choice Academy", "city": "Parañaque City", "schoolID": 407023},
    {"schoolName": "Olivarez College", "city": "Parañaque City", "schoolID": 407041},
    {"schoolName": "St. Andrew's School", "city": "Parañaque City", "schoolID": 407052},
    {"schoolName": "St. Paul College", "city": "Parañaque City", "schoolID": 407059},
    {"schoolName": "United Christian Academy", "city": "Parañaque City", "schoolID": 407070},
    {"schoolName": "Veritas Parochial School", "city": "Parañaque City", "schoolID": 407072},
    {"schoolName": "Marymount Academy", "city": "Parañaque City", "schoolID": 407673},
    {"schoolName": "Manila Tytana Colleges", "city": "Pasay City", "schoolID": 401414},
    {"schoolName": "San Juan de Dios Foundation", "city": "Pasay City", "schoolID": 401429},
    {"schoolName": "STI Pasay", "city": "Pasay City", "schoolID": 401430},
    {"schoolName": "MFI Foundation", "city": "Pasay City", "schoolID": 406528}

  ]
  
  let parentDiv = document.getElementById('data');
  
  for (let index = 0; index < data.length; index++) {
    let div = document.createElement('div');
    div.className = 'schoolcard';
  
    let h1 = document.createElement('h1');
    h1.className = 'schoolname';
    h1.innerHTML = data[index].schoolName;
  
    let addr = document.createElement('p');
    addr.className = 'schooladdr'
    addr.innerHTML = data[index].city;
  
    let id = document.createElement('p');
    id.className = 'schoolid'
    id.innerHTML = data[index].schoolID;
  
    div.appendChild(h1);
    div.appendChild(addr);
    div.appendChild(id);
    parentDiv.appendChild(div);
  }
  
  
  